/* automatically generated by rust-bindgen 0.72.1 */

#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]

pub type vision_ui_switch_changed_cb = ::std::option::Option<
    unsafe extern "C" fn(ui: *mut vision_ui_t, value: bool, user_data: *mut ::std::os::raw::c_void),
>;
pub type vision_ui_slider_changed_cb = ::std::option::Option<
    unsafe extern "C" fn(ui: *mut vision_ui_t, value: i16, user_data: *mut ::std::os::raw::c_void),
>;
pub type vision_ui_scene_cb = ::std::option::Option<
    unsafe extern "C" fn(ui: *mut vision_ui_t, user_data: *mut ::std::os::raw::c_void),
>;
#[doc = " Font configuration passed to the public font setter and driver APIs."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vision_ui_font_t {
    #[doc = " Backend font object, such as a u8g2 font pointer."]
    pub font: *const ::std::os::raw::c_void,
    #[doc = " Adjusts text metrics upward when the font baseline sits too low."]
    pub top_compensation: i8,
    #[doc = " Adjusts text metrics downward when the font clips or sits too high."]
    pub bottom_compensation: i8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vision_ui_font_t"][::std::mem::size_of::<vision_ui_font_t>() - 16usize];
    ["Alignment of vision_ui_font_t"][::std::mem::align_of::<vision_ui_font_t>() - 8usize];
    ["Offset of field: vision_ui_font_t::font"]
        [::std::mem::offset_of!(vision_ui_font_t, font) - 0usize];
    ["Offset of field: vision_ui_font_t::top_compensation"]
        [::std::mem::offset_of!(vision_ui_font_t, top_compensation) - 8usize];
    ["Offset of field: vision_ui_font_t::bottom_compensation"]
        [::std::mem::offset_of!(vision_ui_font_t, bottom_compensation) - 9usize];
};
#[doc = " Shared bitmap pack used by the list icon renderer."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vision_ui_list_icon_t {
    #[doc = " Header bitmap for a plain list container."]
    pub list_header: *const u8,
    #[doc = " Header bitmap for a switch item."]
    pub switch_header: *const u8,
    #[doc = " Header bitmap for a slider item."]
    pub slider_header: *const u8,
    #[doc = " Header bitmap for other list item styles."]
    pub default_header: *const u8,
    #[doc = " Footer bitmap for an enabled switch item."]
    pub switch_on_footer: *const u8,
    #[doc = " Footer bitmap for a disabled switch item."]
    pub switch_off_footer: *const u8,
    #[doc = " Footer bitmap for a slider item."]
    pub slider_footer: *const u8,
    #[doc = " Shared width of header bitmaps."]
    pub header_width: usize,
    #[doc = " Shared height of header bitmaps."]
    pub header_height: usize,
    #[doc = " Shared width of footer bitmaps."]
    pub footer_width: usize,
    #[doc = " Shared height of footer bitmaps."]
    pub footer_height: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vision_ui_list_icon_t"][::std::mem::size_of::<vision_ui_list_icon_t>() - 88usize];
    ["Alignment of vision_ui_list_icon_t"]
        [::std::mem::align_of::<vision_ui_list_icon_t>() - 8usize];
    ["Offset of field: vision_ui_list_icon_t::list_header"]
        [::std::mem::offset_of!(vision_ui_list_icon_t, list_header) - 0usize];
    ["Offset of field: vision_ui_list_icon_t::switch_header"]
        [::std::mem::offset_of!(vision_ui_list_icon_t, switch_header) - 8usize];
    ["Offset of field: vision_ui_list_icon_t::slider_header"]
        [::std::mem::offset_of!(vision_ui_list_icon_t, slider_header) - 16usize];
    ["Offset of field: vision_ui_list_icon_t::default_header"]
        [::std::mem::offset_of!(vision_ui_list_icon_t, default_header) - 24usize];
    ["Offset of field: vision_ui_list_icon_t::switch_on_footer"]
        [::std::mem::offset_of!(vision_ui_list_icon_t, switch_on_footer) - 32usize];
    ["Offset of field: vision_ui_list_icon_t::switch_off_footer"]
        [::std::mem::offset_of!(vision_ui_list_icon_t, switch_off_footer) - 40usize];
    ["Offset of field: vision_ui_list_icon_t::slider_footer"]
        [::std::mem::offset_of!(vision_ui_list_icon_t, slider_footer) - 48usize];
    ["Offset of field: vision_ui_list_icon_t::header_width"]
        [::std::mem::offset_of!(vision_ui_list_icon_t, header_width) - 56usize];
    ["Offset of field: vision_ui_list_icon_t::header_height"]
        [::std::mem::offset_of!(vision_ui_list_icon_t, header_height) - 64usize];
    ["Offset of field: vision_ui_list_icon_t::footer_width"]
        [::std::mem::offset_of!(vision_ui_list_icon_t, footer_width) - 72usize];
    ["Offset of field: vision_ui_list_icon_t::footer_height"]
        [::std::mem::offset_of!(vision_ui_list_icon_t, footer_height) - 80usize];
};
#[doc = " Shared bitmap pack used by the list icon renderer."]
pub type vision_ui_icon_t = vision_ui_list_icon_t;
pub const vision_ui_action_t_UiActionNone: vision_ui_action_t = 0;
pub const vision_ui_action_t_UiActionGoPrev: vision_ui_action_t = 1;
pub const vision_ui_action_t_UiActionGoNext: vision_ui_action_t = 2;
pub const vision_ui_action_t_UiActionEnter: vision_ui_action_t = 3;
pub const vision_ui_action_t_UiActionExit: vision_ui_action_t = 4;
#[doc = " High-level input actions consumed by Vision UI."]
pub type vision_ui_action_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vision_ui_notification_t {
    pub content: *const ::std::os::raw::c_char,
    pub span: u16,
    pub y_notification: f32,
    pub y_notification_trg: f32,
    pub w_notification: f32,
    pub w_notification_trg: f32,
    pub is_running: bool,
    pub time_start: u32,
    pub time: u32,
    pub is_dismissing: bool,
    pub dismiss_start: u32,
    pub pending_content: *const ::std::os::raw::c_char,
    pub pending_span: u16,
    pub has_pending: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vision_ui_notification_t"]
        [::std::mem::size_of::<vision_ui_notification_t>() - 64usize];
    ["Alignment of vision_ui_notification_t"]
        [::std::mem::align_of::<vision_ui_notification_t>() - 8usize];
    ["Offset of field: vision_ui_notification_t::content"]
        [::std::mem::offset_of!(vision_ui_notification_t, content) - 0usize];
    ["Offset of field: vision_ui_notification_t::span"]
        [::std::mem::offset_of!(vision_ui_notification_t, span) - 8usize];
    ["Offset of field: vision_ui_notification_t::y_notification"]
        [::std::mem::offset_of!(vision_ui_notification_t, y_notification) - 12usize];
    ["Offset of field: vision_ui_notification_t::y_notification_trg"]
        [::std::mem::offset_of!(vision_ui_notification_t, y_notification_trg) - 16usize];
    ["Offset of field: vision_ui_notification_t::w_notification"]
        [::std::mem::offset_of!(vision_ui_notification_t, w_notification) - 20usize];
    ["Offset of field: vision_ui_notification_t::w_notification_trg"]
        [::std::mem::offset_of!(vision_ui_notification_t, w_notification_trg) - 24usize];
    ["Offset of field: vision_ui_notification_t::is_running"]
        [::std::mem::offset_of!(vision_ui_notification_t, is_running) - 28usize];
    ["Offset of field: vision_ui_notification_t::time_start"]
        [::std::mem::offset_of!(vision_ui_notification_t, time_start) - 32usize];
    ["Offset of field: vision_ui_notification_t::time"]
        [::std::mem::offset_of!(vision_ui_notification_t, time) - 36usize];
    ["Offset of field: vision_ui_notification_t::is_dismissing"]
        [::std::mem::offset_of!(vision_ui_notification_t, is_dismissing) - 40usize];
    ["Offset of field: vision_ui_notification_t::dismiss_start"]
        [::std::mem::offset_of!(vision_ui_notification_t, dismiss_start) - 44usize];
    ["Offset of field: vision_ui_notification_t::pending_content"]
        [::std::mem::offset_of!(vision_ui_notification_t, pending_content) - 48usize];
    ["Offset of field: vision_ui_notification_t::pending_span"]
        [::std::mem::offset_of!(vision_ui_notification_t, pending_span) - 56usize];
    ["Offset of field: vision_ui_notification_t::has_pending"]
        [::std::mem::offset_of!(vision_ui_notification_t, has_pending) - 58usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vision_ui_alert_t {
    pub content: *const ::std::os::raw::c_char,
    pub span: u16,
    pub y_alert: f32,
    pub y_alert_trg: f32,
    pub w_alert: f32,
    pub w_alert_trg: f32,
    pub is_running: bool,
    pub time_start: u32,
    pub time: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vision_ui_alert_t"][::std::mem::size_of::<vision_ui_alert_t>() - 40usize];
    ["Alignment of vision_ui_alert_t"][::std::mem::align_of::<vision_ui_alert_t>() - 8usize];
    ["Offset of field: vision_ui_alert_t::content"]
        [::std::mem::offset_of!(vision_ui_alert_t, content) - 0usize];
    ["Offset of field: vision_ui_alert_t::span"]
        [::std::mem::offset_of!(vision_ui_alert_t, span) - 8usize];
    ["Offset of field: vision_ui_alert_t::y_alert"]
        [::std::mem::offset_of!(vision_ui_alert_t, y_alert) - 12usize];
    ["Offset of field: vision_ui_alert_t::y_alert_trg"]
        [::std::mem::offset_of!(vision_ui_alert_t, y_alert_trg) - 16usize];
    ["Offset of field: vision_ui_alert_t::w_alert"]
        [::std::mem::offset_of!(vision_ui_alert_t, w_alert) - 20usize];
    ["Offset of field: vision_ui_alert_t::w_alert_trg"]
        [::std::mem::offset_of!(vision_ui_alert_t, w_alert_trg) - 24usize];
    ["Offset of field: vision_ui_alert_t::is_running"]
        [::std::mem::offset_of!(vision_ui_alert_t, is_running) - 28usize];
    ["Offset of field: vision_ui_alert_t::time_start"]
        [::std::mem::offset_of!(vision_ui_alert_t, time_start) - 32usize];
    ["Offset of field: vision_ui_alert_t::time"]
        [::std::mem::offset_of!(vision_ui_alert_t, time) - 36usize];
};
pub const vision_ui_list_item_type_t_ListItem: vision_ui_list_item_type_t = 0;
pub const vision_ui_list_item_type_t_TitleItem: vision_ui_list_item_type_t = 1;
pub const vision_ui_list_item_type_t_IconItem: vision_ui_list_item_type_t = 2;
pub const vision_ui_list_item_type_t_SwitchItem: vision_ui_list_item_type_t = 3;
pub const vision_ui_list_item_type_t_SliderItem: vision_ui_list_item_type_t = 4;
pub const vision_ui_list_item_type_t_UserItem: vision_ui_list_item_type_t = 5;
pub type vision_ui_list_item_type_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vision_ui_list_item_t {
    pub type_: vision_ui_list_item_type_t,
    pub icon_view_mode: bool,
    pub owns_child_list: bool,
    pub content: *const ::std::os::raw::c_char,
    pub text_scroll_anchor: u32,
    pub scroll_bar_top: f32,
    pub scroll_bar_top_velocity: f32,
    pub scroll_bar_top_trg: f32,
    pub scroll_bar_height: f32,
    pub scroll_bar_height_velocity: f32,
    pub scroll_bar_height_trg: f32,
    pub scroll_bar_scale_part: f32,
    pub scroll_bar_scale_part_trg: f32,
    pub scroll_bar_top_px: i16,
    pub scroll_bar_height_px: i16,
    pub y_list_item: f32,
    pub y_list_item_trg: f32,
    pub icon_scroll_offset: f32,
    pub icon_scroll_offset_velocity: f32,
    pub icon_scroll_offset_trg: f32,
    pub layer: u8,
    pub child_num: u8,
    pub capacity: usize,
    pub child_list_item: *mut *mut vision_ui_list_item_t,
    pub parent: *mut vision_ui_list_item_t,
    pub owned_next: *mut vision_ui_list_item_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vision_ui_list_item_t"][::std::mem::size_of::<vision_ui_list_item_t>() - 112usize];
    ["Alignment of vision_ui_list_item_t"]
        [::std::mem::align_of::<vision_ui_list_item_t>() - 8usize];
    ["Offset of field: vision_ui_list_item_t::type_"]
        [::std::mem::offset_of!(vision_ui_list_item_t, type_) - 0usize];
    ["Offset of field: vision_ui_list_item_t::icon_view_mode"]
        [::std::mem::offset_of!(vision_ui_list_item_t, icon_view_mode) - 4usize];
    ["Offset of field: vision_ui_list_item_t::owns_child_list"]
        [::std::mem::offset_of!(vision_ui_list_item_t, owns_child_list) - 5usize];
    ["Offset of field: vision_ui_list_item_t::content"]
        [::std::mem::offset_of!(vision_ui_list_item_t, content) - 8usize];
    ["Offset of field: vision_ui_list_item_t::text_scroll_anchor"]
        [::std::mem::offset_of!(vision_ui_list_item_t, text_scroll_anchor) - 16usize];
    ["Offset of field: vision_ui_list_item_t::scroll_bar_top"]
        [::std::mem::offset_of!(vision_ui_list_item_t, scroll_bar_top) - 20usize];
    ["Offset of field: vision_ui_list_item_t::scroll_bar_top_velocity"]
        [::std::mem::offset_of!(vision_ui_list_item_t, scroll_bar_top_velocity) - 24usize];
    ["Offset of field: vision_ui_list_item_t::scroll_bar_top_trg"]
        [::std::mem::offset_of!(vision_ui_list_item_t, scroll_bar_top_trg) - 28usize];
    ["Offset of field: vision_ui_list_item_t::scroll_bar_height"]
        [::std::mem::offset_of!(vision_ui_list_item_t, scroll_bar_height) - 32usize];
    ["Offset of field: vision_ui_list_item_t::scroll_bar_height_velocity"]
        [::std::mem::offset_of!(vision_ui_list_item_t, scroll_bar_height_velocity) - 36usize];
    ["Offset of field: vision_ui_list_item_t::scroll_bar_height_trg"]
        [::std::mem::offset_of!(vision_ui_list_item_t, scroll_bar_height_trg) - 40usize];
    ["Offset of field: vision_ui_list_item_t::scroll_bar_scale_part"]
        [::std::mem::offset_of!(vision_ui_list_item_t, scroll_bar_scale_part) - 44usize];
    ["Offset of field: vision_ui_list_item_t::scroll_bar_scale_part_trg"]
        [::std::mem::offset_of!(vision_ui_list_item_t, scroll_bar_scale_part_trg) - 48usize];
    ["Offset of field: vision_ui_list_item_t::scroll_bar_top_px"]
        [::std::mem::offset_of!(vision_ui_list_item_t, scroll_bar_top_px) - 52usize];
    ["Offset of field: vision_ui_list_item_t::scroll_bar_height_px"]
        [::std::mem::offset_of!(vision_ui_list_item_t, scroll_bar_height_px) - 54usize];
    ["Offset of field: vision_ui_list_item_t::y_list_item"]
        [::std::mem::offset_of!(vision_ui_list_item_t, y_list_item) - 56usize];
    ["Offset of field: vision_ui_list_item_t::y_list_item_trg"]
        [::std::mem::offset_of!(vision_ui_list_item_t, y_list_item_trg) - 60usize];
    ["Offset of field: vision_ui_list_item_t::icon_scroll_offset"]
        [::std::mem::offset_of!(vision_ui_list_item_t, icon_scroll_offset) - 64usize];
    ["Offset of field: vision_ui_list_item_t::icon_scroll_offset_velocity"]
        [::std::mem::offset_of!(vision_ui_list_item_t, icon_scroll_offset_velocity) - 68usize];
    ["Offset of field: vision_ui_list_item_t::icon_scroll_offset_trg"]
        [::std::mem::offset_of!(vision_ui_list_item_t, icon_scroll_offset_trg) - 72usize];
    ["Offset of field: vision_ui_list_item_t::layer"]
        [::std::mem::offset_of!(vision_ui_list_item_t, layer) - 76usize];
    ["Offset of field: vision_ui_list_item_t::child_num"]
        [::std::mem::offset_of!(vision_ui_list_item_t, child_num) - 77usize];
    ["Offset of field: vision_ui_list_item_t::capacity"]
        [::std::mem::offset_of!(vision_ui_list_item_t, capacity) - 80usize];
    ["Offset of field: vision_ui_list_item_t::child_list_item"]
        [::std::mem::offset_of!(vision_ui_list_item_t, child_list_item) - 88usize];
    ["Offset of field: vision_ui_list_item_t::parent"]
        [::std::mem::offset_of!(vision_ui_list_item_t, parent) - 96usize];
    ["Offset of field: vision_ui_list_item_t::owned_next"]
        [::std::mem::offset_of!(vision_ui_list_item_t, owned_next) - 104usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vision_ui_switch_item_t {
    pub base_item: vision_ui_list_item_t,
    pub value: bool,
    pub on_changed: vision_ui_switch_changed_cb,
    pub on_changed_user_data: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vision_ui_switch_item_t"]
        [::std::mem::size_of::<vision_ui_switch_item_t>() - 136usize];
    ["Alignment of vision_ui_switch_item_t"]
        [::std::mem::align_of::<vision_ui_switch_item_t>() - 8usize];
    ["Offset of field: vision_ui_switch_item_t::base_item"]
        [::std::mem::offset_of!(vision_ui_switch_item_t, base_item) - 0usize];
    ["Offset of field: vision_ui_switch_item_t::value"]
        [::std::mem::offset_of!(vision_ui_switch_item_t, value) - 112usize];
    ["Offset of field: vision_ui_switch_item_t::on_changed"]
        [::std::mem::offset_of!(vision_ui_switch_item_t, on_changed) - 120usize];
    ["Offset of field: vision_ui_switch_item_t::on_changed_user_data"]
        [::std::mem::offset_of!(vision_ui_switch_item_t, on_changed_user_data) - 128usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vision_ui_slider_item_t {
    pub base_item: vision_ui_list_item_t,
    pub value: i16,
    pub is_confirmed: bool,
    pub value_step: u8,
    pub value_max: i16,
    pub value_min: i16,
    pub text_scroll_anchor: u32,
    pub on_changed: vision_ui_slider_changed_cb,
    pub on_changed_user_data: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vision_ui_slider_item_t"]
        [::std::mem::size_of::<vision_ui_slider_item_t>() - 144usize];
    ["Alignment of vision_ui_slider_item_t"]
        [::std::mem::align_of::<vision_ui_slider_item_t>() - 8usize];
    ["Offset of field: vision_ui_slider_item_t::base_item"]
        [::std::mem::offset_of!(vision_ui_slider_item_t, base_item) - 0usize];
    ["Offset of field: vision_ui_slider_item_t::value"]
        [::std::mem::offset_of!(vision_ui_slider_item_t, value) - 112usize];
    ["Offset of field: vision_ui_slider_item_t::is_confirmed"]
        [::std::mem::offset_of!(vision_ui_slider_item_t, is_confirmed) - 114usize];
    ["Offset of field: vision_ui_slider_item_t::value_step"]
        [::std::mem::offset_of!(vision_ui_slider_item_t, value_step) - 115usize];
    ["Offset of field: vision_ui_slider_item_t::value_max"]
        [::std::mem::offset_of!(vision_ui_slider_item_t, value_max) - 116usize];
    ["Offset of field: vision_ui_slider_item_t::value_min"]
        [::std::mem::offset_of!(vision_ui_slider_item_t, value_min) - 118usize];
    ["Offset of field: vision_ui_slider_item_t::text_scroll_anchor"]
        [::std::mem::offset_of!(vision_ui_slider_item_t, text_scroll_anchor) - 120usize];
    ["Offset of field: vision_ui_slider_item_t::on_changed"]
        [::std::mem::offset_of!(vision_ui_slider_item_t, on_changed) - 128usize];
    ["Offset of field: vision_ui_slider_item_t::on_changed_user_data"]
        [::std::mem::offset_of!(vision_ui_slider_item_t, on_changed_user_data) - 136usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vision_ui_title_item_t {
    pub base_item: vision_ui_list_item_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vision_ui_title_item_t"][::std::mem::size_of::<vision_ui_title_item_t>() - 112usize];
    ["Alignment of vision_ui_title_item_t"]
        [::std::mem::align_of::<vision_ui_title_item_t>() - 8usize];
    ["Offset of field: vision_ui_title_item_t::base_item"]
        [::std::mem::offset_of!(vision_ui_title_item_t, base_item) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vision_ui_icon_item_t {
    pub base_item: vision_ui_list_item_t,
    pub title_y: f32,
    pub title_y_velocity: f32,
    pub title_y_trg: f32,
    pub icon: *const u8,
    pub description: *const ::std::os::raw::c_char,
    pub description_scroll_anchor: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vision_ui_icon_item_t"][::std::mem::size_of::<vision_ui_icon_item_t>() - 152usize];
    ["Alignment of vision_ui_icon_item_t"]
        [::std::mem::align_of::<vision_ui_icon_item_t>() - 8usize];
    ["Offset of field: vision_ui_icon_item_t::base_item"]
        [::std::mem::offset_of!(vision_ui_icon_item_t, base_item) - 0usize];
    ["Offset of field: vision_ui_icon_item_t::title_y"]
        [::std::mem::offset_of!(vision_ui_icon_item_t, title_y) - 112usize];
    ["Offset of field: vision_ui_icon_item_t::title_y_velocity"]
        [::std::mem::offset_of!(vision_ui_icon_item_t, title_y_velocity) - 116usize];
    ["Offset of field: vision_ui_icon_item_t::title_y_trg"]
        [::std::mem::offset_of!(vision_ui_icon_item_t, title_y_trg) - 120usize];
    ["Offset of field: vision_ui_icon_item_t::icon"]
        [::std::mem::offset_of!(vision_ui_icon_item_t, icon) - 128usize];
    ["Offset of field: vision_ui_icon_item_t::description"]
        [::std::mem::offset_of!(vision_ui_icon_item_t, description) - 136usize];
    ["Offset of field: vision_ui_icon_item_t::description_scroll_anchor"]
        [::std::mem::offset_of!(vision_ui_icon_item_t, description_scroll_anchor) - 144usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vision_ui_user_item_t {
    pub base_item: vision_ui_list_item_t,
    pub in_user_item: bool,
    pub entering_user_item: bool,
    pub exiting_user_item: bool,
    pub init_function: vision_ui_scene_cb,
    pub loop_function: vision_ui_scene_cb,
    pub exit_function: vision_ui_scene_cb,
    pub user_data: *mut ::std::os::raw::c_void,
    pub user_item_inited: bool,
    pub user_item_looping: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vision_ui_user_item_t"][::std::mem::size_of::<vision_ui_user_item_t>() - 160usize];
    ["Alignment of vision_ui_user_item_t"]
        [::std::mem::align_of::<vision_ui_user_item_t>() - 8usize];
    ["Offset of field: vision_ui_user_item_t::base_item"]
        [::std::mem::offset_of!(vision_ui_user_item_t, base_item) - 0usize];
    ["Offset of field: vision_ui_user_item_t::in_user_item"]
        [::std::mem::offset_of!(vision_ui_user_item_t, in_user_item) - 112usize];
    ["Offset of field: vision_ui_user_item_t::entering_user_item"]
        [::std::mem::offset_of!(vision_ui_user_item_t, entering_user_item) - 113usize];
    ["Offset of field: vision_ui_user_item_t::exiting_user_item"]
        [::std::mem::offset_of!(vision_ui_user_item_t, exiting_user_item) - 114usize];
    ["Offset of field: vision_ui_user_item_t::init_function"]
        [::std::mem::offset_of!(vision_ui_user_item_t, init_function) - 120usize];
    ["Offset of field: vision_ui_user_item_t::loop_function"]
        [::std::mem::offset_of!(vision_ui_user_item_t, loop_function) - 128usize];
    ["Offset of field: vision_ui_user_item_t::exit_function"]
        [::std::mem::offset_of!(vision_ui_user_item_t, exit_function) - 136usize];
    ["Offset of field: vision_ui_user_item_t::user_data"]
        [::std::mem::offset_of!(vision_ui_user_item_t, user_data) - 144usize];
    ["Offset of field: vision_ui_user_item_t::user_item_inited"]
        [::std::mem::offset_of!(vision_ui_user_item_t, user_item_inited) - 152usize];
    ["Offset of field: vision_ui_user_item_t::user_item_looping"]
        [::std::mem::offset_of!(vision_ui_user_item_t, user_item_looping) - 153usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vision_ui_selector_t {
    pub y_selector: f32,
    pub y_selector_velocity: f32,
    pub y_selector_trg: f32,
    pub w_selector: f32,
    pub w_selector_velocity: f32,
    pub w_selector_trg: f32,
    pub h_selector: f32,
    pub h_selector_velocity: f32,
    pub h_selector_trg: f32,
    pub selected_index: u8,
    pub selected_item: *mut vision_ui_list_item_t,
    pub scroll_bar_scale_parent: *mut vision_ui_list_item_t,
    pub scroll_bar_scale_part_shared: f32,
    pub has_pending_selection: bool,
    pub pending_selected_index: u8,
    pub pending_selected_item: *mut vision_ui_list_item_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vision_ui_selector_t"][::std::mem::size_of::<vision_ui_selector_t>() - 72usize];
    ["Alignment of vision_ui_selector_t"][::std::mem::align_of::<vision_ui_selector_t>() - 8usize];
    ["Offset of field: vision_ui_selector_t::y_selector"]
        [::std::mem::offset_of!(vision_ui_selector_t, y_selector) - 0usize];
    ["Offset of field: vision_ui_selector_t::y_selector_velocity"]
        [::std::mem::offset_of!(vision_ui_selector_t, y_selector_velocity) - 4usize];
    ["Offset of field: vision_ui_selector_t::y_selector_trg"]
        [::std::mem::offset_of!(vision_ui_selector_t, y_selector_trg) - 8usize];
    ["Offset of field: vision_ui_selector_t::w_selector"]
        [::std::mem::offset_of!(vision_ui_selector_t, w_selector) - 12usize];
    ["Offset of field: vision_ui_selector_t::w_selector_velocity"]
        [::std::mem::offset_of!(vision_ui_selector_t, w_selector_velocity) - 16usize];
    ["Offset of field: vision_ui_selector_t::w_selector_trg"]
        [::std::mem::offset_of!(vision_ui_selector_t, w_selector_trg) - 20usize];
    ["Offset of field: vision_ui_selector_t::h_selector"]
        [::std::mem::offset_of!(vision_ui_selector_t, h_selector) - 24usize];
    ["Offset of field: vision_ui_selector_t::h_selector_velocity"]
        [::std::mem::offset_of!(vision_ui_selector_t, h_selector_velocity) - 28usize];
    ["Offset of field: vision_ui_selector_t::h_selector_trg"]
        [::std::mem::offset_of!(vision_ui_selector_t, h_selector_trg) - 32usize];
    ["Offset of field: vision_ui_selector_t::selected_index"]
        [::std::mem::offset_of!(vision_ui_selector_t, selected_index) - 36usize];
    ["Offset of field: vision_ui_selector_t::selected_item"]
        [::std::mem::offset_of!(vision_ui_selector_t, selected_item) - 40usize];
    ["Offset of field: vision_ui_selector_t::scroll_bar_scale_parent"]
        [::std::mem::offset_of!(vision_ui_selector_t, scroll_bar_scale_parent) - 48usize];
    ["Offset of field: vision_ui_selector_t::scroll_bar_scale_part_shared"]
        [::std::mem::offset_of!(vision_ui_selector_t, scroll_bar_scale_part_shared) - 56usize];
    ["Offset of field: vision_ui_selector_t::has_pending_selection"]
        [::std::mem::offset_of!(vision_ui_selector_t, has_pending_selection) - 60usize];
    ["Offset of field: vision_ui_selector_t::pending_selected_index"]
        [::std::mem::offset_of!(vision_ui_selector_t, pending_selected_index) - 61usize];
    ["Offset of field: vision_ui_selector_t::pending_selected_item"]
        [::std::mem::offset_of!(vision_ui_selector_t, pending_selected_item) - 64usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vision_ui_camera_t {
    pub x_camera: f32,
    pub x_camera_velocity: f32,
    pub x_camera_trg: f32,
    pub y_camera: f32,
    pub y_camera_velocity: f32,
    pub y_camera_trg: f32,
    pub selector: *mut vision_ui_selector_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vision_ui_camera_t"][::std::mem::size_of::<vision_ui_camera_t>() - 32usize];
    ["Alignment of vision_ui_camera_t"][::std::mem::align_of::<vision_ui_camera_t>() - 8usize];
    ["Offset of field: vision_ui_camera_t::x_camera"]
        [::std::mem::offset_of!(vision_ui_camera_t, x_camera) - 0usize];
    ["Offset of field: vision_ui_camera_t::x_camera_velocity"]
        [::std::mem::offset_of!(vision_ui_camera_t, x_camera_velocity) - 4usize];
    ["Offset of field: vision_ui_camera_t::x_camera_trg"]
        [::std::mem::offset_of!(vision_ui_camera_t, x_camera_trg) - 8usize];
    ["Offset of field: vision_ui_camera_t::y_camera"]
        [::std::mem::offset_of!(vision_ui_camera_t, y_camera) - 12usize];
    ["Offset of field: vision_ui_camera_t::y_camera_velocity"]
        [::std::mem::offset_of!(vision_ui_camera_t, y_camera_velocity) - 16usize];
    ["Offset of field: vision_ui_camera_t::y_camera_trg"]
        [::std::mem::offset_of!(vision_ui_camera_t, y_camera_trg) - 20usize];
    ["Offset of field: vision_ui_camera_t::selector"]
        [::std::mem::offset_of!(vision_ui_camera_t, selector) - 24usize];
};
pub const vision_alloc_op_t_VisionAllocMalloc: vision_alloc_op_t = 0;
pub const vision_alloc_op_t_VisionAllocCalloc: vision_alloc_op_t = 1;
pub const vision_alloc_op_t_VisionAllocFree: vision_alloc_op_t = 2;
pub type vision_alloc_op_t = ::std::os::raw::c_uint;
pub type vision_ui_allocator_t = ::std::option::Option<
    unsafe extern "C" fn(
        op: vision_alloc_op_t,
        size: usize,
        count: usize,
        ptr: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vision_ui_t {
    pub is_in_vision_ui: bool,
    pub is_background_frozen: bool,
    pub owns_self: bool,
    pub logo: *const u8,
    pub logo_span: u32,
    pub last_tick: u32,
    pub logo_finished: bool,
    pub logo_started: bool,
    pub logo_start_time: u32,
    pub exit_animation_finished: bool,
    pub enter_animation_finished: bool,
    pub exit_elapsed_ms: f32,
    pub running_exit: bool,
    pub enter_elapsed_ms: f32,
    pub running_enter: bool,
    pub minifont: vision_ui_font_t,
    pub font: vision_ui_font_t,
    pub title_font: vision_ui_font_t,
    pub subtitle_font: vision_ui_font_t,
    pub allocator: vision_ui_allocator_t,
    pub notification: vision_ui_notification_t,
    pub alert: vision_ui_alert_t,
    pub selector: vision_ui_selector_t,
    pub camera: vision_ui_camera_t,
    pub root_item: *mut vision_ui_list_item_t,
    pub owned_item_head: *mut vision_ui_list_item_t,
    pub list_icon: vision_ui_icon_t,
    pub driver: *mut ::std::os::raw::c_void,
    pub driver_current_font: vision_ui_font_t,
    pub driver_str_top: i8,
    pub driver_str_bottom: i8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vision_ui_t"][::std::mem::size_of::<vision_ui_t>() - 472usize];
    ["Alignment of vision_ui_t"][::std::mem::align_of::<vision_ui_t>() - 8usize];
    ["Offset of field: vision_ui_t::is_in_vision_ui"]
        [::std::mem::offset_of!(vision_ui_t, is_in_vision_ui) - 0usize];
    ["Offset of field: vision_ui_t::is_background_frozen"]
        [::std::mem::offset_of!(vision_ui_t, is_background_frozen) - 1usize];
    ["Offset of field: vision_ui_t::owns_self"]
        [::std::mem::offset_of!(vision_ui_t, owns_self) - 2usize];
    ["Offset of field: vision_ui_t::logo"][::std::mem::offset_of!(vision_ui_t, logo) - 8usize];
    ["Offset of field: vision_ui_t::logo_span"]
        [::std::mem::offset_of!(vision_ui_t, logo_span) - 16usize];
    ["Offset of field: vision_ui_t::last_tick"]
        [::std::mem::offset_of!(vision_ui_t, last_tick) - 20usize];
    ["Offset of field: vision_ui_t::logo_finished"]
        [::std::mem::offset_of!(vision_ui_t, logo_finished) - 24usize];
    ["Offset of field: vision_ui_t::logo_started"]
        [::std::mem::offset_of!(vision_ui_t, logo_started) - 25usize];
    ["Offset of field: vision_ui_t::logo_start_time"]
        [::std::mem::offset_of!(vision_ui_t, logo_start_time) - 28usize];
    ["Offset of field: vision_ui_t::exit_animation_finished"]
        [::std::mem::offset_of!(vision_ui_t, exit_animation_finished) - 32usize];
    ["Offset of field: vision_ui_t::enter_animation_finished"]
        [::std::mem::offset_of!(vision_ui_t, enter_animation_finished) - 33usize];
    ["Offset of field: vision_ui_t::exit_elapsed_ms"]
        [::std::mem::offset_of!(vision_ui_t, exit_elapsed_ms) - 36usize];
    ["Offset of field: vision_ui_t::running_exit"]
        [::std::mem::offset_of!(vision_ui_t, running_exit) - 40usize];
    ["Offset of field: vision_ui_t::enter_elapsed_ms"]
        [::std::mem::offset_of!(vision_ui_t, enter_elapsed_ms) - 44usize];
    ["Offset of field: vision_ui_t::running_enter"]
        [::std::mem::offset_of!(vision_ui_t, running_enter) - 48usize];
    ["Offset of field: vision_ui_t::minifont"]
        [::std::mem::offset_of!(vision_ui_t, minifont) - 56usize];
    ["Offset of field: vision_ui_t::font"][::std::mem::offset_of!(vision_ui_t, font) - 72usize];
    ["Offset of field: vision_ui_t::title_font"]
        [::std::mem::offset_of!(vision_ui_t, title_font) - 88usize];
    ["Offset of field: vision_ui_t::subtitle_font"]
        [::std::mem::offset_of!(vision_ui_t, subtitle_font) - 104usize];
    ["Offset of field: vision_ui_t::allocator"]
        [::std::mem::offset_of!(vision_ui_t, allocator) - 120usize];
    ["Offset of field: vision_ui_t::notification"]
        [::std::mem::offset_of!(vision_ui_t, notification) - 128usize];
    ["Offset of field: vision_ui_t::alert"][::std::mem::offset_of!(vision_ui_t, alert) - 192usize];
    ["Offset of field: vision_ui_t::selector"]
        [::std::mem::offset_of!(vision_ui_t, selector) - 232usize];
    ["Offset of field: vision_ui_t::camera"]
        [::std::mem::offset_of!(vision_ui_t, camera) - 304usize];
    ["Offset of field: vision_ui_t::root_item"]
        [::std::mem::offset_of!(vision_ui_t, root_item) - 336usize];
    ["Offset of field: vision_ui_t::owned_item_head"]
        [::std::mem::offset_of!(vision_ui_t, owned_item_head) - 344usize];
    ["Offset of field: vision_ui_t::list_icon"]
        [::std::mem::offset_of!(vision_ui_t, list_icon) - 352usize];
    ["Offset of field: vision_ui_t::driver"]
        [::std::mem::offset_of!(vision_ui_t, driver) - 440usize];
    ["Offset of field: vision_ui_t::driver_current_font"]
        [::std::mem::offset_of!(vision_ui_t, driver_current_font) - 448usize];
    ["Offset of field: vision_ui_t::driver_str_top"]
        [::std::mem::offset_of!(vision_ui_t, driver_str_top) - 464usize];
    ["Offset of field: vision_ui_t::driver_str_bottom"]
        [::std::mem::offset_of!(vision_ui_t, driver_str_bottom) - 465usize];
};
unsafe extern "C" {
    pub fn vision_ui_smoothstep(t: f32) -> f32;
    pub fn vision_ui_animation_s_curve(pos: *mut f32, pos_trg: f32, speed: f32, delta_ms: f32);
    pub fn vision_ui_animation_2nd_ode_no_overshoot(
        pos: *mut f32,
        velocity: *mut f32,
        post_trg: f32,
        speed: f32,
        delta_ms: f32,
    );
    pub fn vision_ui_animation_2nd_ode_slight_overshoot(
        pos: *mut f32,
        velocity: *mut f32,
        post_trg: f32,
        speed: f32,
        delta_ms: f32,
    );
    #[doc = " Initializes a caller-owned UI instance before first use.\n\n @param ui UI instance to initialize. Must not be `NULL`."]
    pub fn vision_ui_init(ui: *mut vision_ui_t);
    #[doc = " Allocates and initializes a heap-owned UI instance.\n\n @return A non-`NULL` UI instance on success, or `NULL` when heap allocation fails."]
    pub fn vision_ui_create() -> *mut vision_ui_t;
    #[doc = " Destroys a UI instance and any library-owned items created for it.\n\n If `ui` was created by `vision_ui_create()`, this also frees the UI object itself. If `ui` was initialized with\n `vision_ui_init()`, the caller still owns the storage for the struct.\n\n @param ui UI instance to destroy, or `NULL` to do nothing."]
    pub fn vision_ui_destroy(ui: *mut vision_ui_t);
    #[doc = " Marks the UI as active and prepares the renderer to start drawing.\n\n @param ui UI instance to activate. Must not be `NULL`."]
    pub fn vision_ui_render_init(ui: *mut vision_ui_t);
    #[doc = " Initializes selector, camera, and list runtime state after the tree is built.\n\n The root tree should already be attached with `vision_ui_root_item_set()` before this is called.\n\n @param ui UI instance to initialize. Must not be `NULL`."]
    pub fn vision_ui_core_init(ui: *mut vision_ui_t);
    #[doc = " Shows a startup bitmap for a fixed duration before the normal UI loop takes over.\n\n @param ui UI instance to configure. Must not be `NULL`.\n @param bmp Monochrome bitmap pointer to display. The pointer is borrowed, not copied.\n @param span Display duration in milliseconds."]
    pub fn vision_ui_start_logo_set(ui: *mut vision_ui_t, bmp: *const u8, span: u32);
    #[doc = " Runs one frame of UI logic and rendering.\n\n @param ui UI instance to update and render. Must not be `NULL`."]
    pub fn vision_ui_step_render(ui: *mut vision_ui_t);
    #[doc = " Returns whether the UI has completed its exit flow.\n\n @param ui UI instance to query. Must not be `NULL`.\n @return `true` when the UI is no longer active; otherwise `false`."]
    pub fn vision_ui_is_exited(ui: *const vision_ui_t) -> bool;
    #[doc = " Returns whether background interaction should be paused behind the UI.\n\n @param ui UI instance to query. Must not be `NULL`.\n @return `true` when background interaction should be frozen; otherwise `false`."]
    pub fn vision_ui_is_background_frozen(ui: *const vision_ui_t) -> bool;
    #[doc = " Installs a custom allocator used for subsequent library-managed allocations.\n\n Constructor-created items allocated after this call will use the supplied allocator, and `vision_ui_destroy()` will\n free those library-owned items through the same allocator.\n\n @param ui UI instance to configure. Must not be `NULL`.\n @param allocator Allocation callback to install, or `NULL` to use the default libc allocator."]
    pub fn vision_ui_allocator_set(ui: *mut vision_ui_t, allocator: vision_ui_allocator_t);
    #[doc = " Sets the small utility font.\n\n @param ui UI instance to configure. Must not be `NULL`.\n @param font Font configuration to store."]
    pub fn vision_ui_minifont_set(ui: *mut vision_ui_t, font: vision_ui_font_t);
    #[doc = " Sets the main body font.\n\n @param ui UI instance to configure. Must not be `NULL`.\n @param font Font configuration to store."]
    pub fn vision_ui_font_set(ui: *mut vision_ui_t, font: vision_ui_font_t);
    #[doc = " Sets the title font.\n\n @param ui UI instance to configure. Must not be `NULL`.\n @param font Font configuration to store."]
    pub fn vision_ui_font_set_title(ui: *mut vision_ui_t, font: vision_ui_font_t);
    #[doc = " Sets the subtitle font.\n\n @param ui UI instance to configure. Must not be `NULL`.\n @param font Font configuration to store."]
    pub fn vision_ui_font_set_subtitle(ui: *mut vision_ui_t, font: vision_ui_font_t);
    #[doc = " Returns the current small utility font.\n\n @param ui UI instance to query. Must not be `NULL`.\n @return A copy of the currently configured minifont. Its `font` field may be `NULL` if no font was configured yet."]
    pub fn vision_ui_minifont_get(ui: *const vision_ui_t) -> vision_ui_font_t;
    #[doc = " Returns the current main body font.\n\n @param ui UI instance to query. Must not be `NULL`.\n @return A copy of the currently configured body font. Its `font` field may be `NULL` if no font was configured yet."]
    pub fn vision_ui_font_get(ui: *const vision_ui_t) -> vision_ui_font_t;
    #[doc = " Returns the current title font.\n\n @param ui UI instance to query. Must not be `NULL`.\n @return A copy of the currently configured title font. Its `font` field may be `NULL` if no font was configured yet."]
    pub fn vision_ui_font_get_title(ui: *const vision_ui_t) -> vision_ui_font_t;
    #[doc = " Returns the current subtitle font.\n\n @param ui UI instance to query. Must not be `NULL`.\n @return A copy of the currently configured subtitle font. Its `font` field may be `NULL` if no font was configured\n yet."]
    pub fn vision_ui_font_get_subtitle(ui: *const vision_ui_t) -> vision_ui_font_t;
    pub fn vision_ui_exit_animation_is_finished(ui: *const vision_ui_t) -> bool;
    pub fn vision_ui_exit_animation_set_is_finished(ui: *mut vision_ui_t);
    pub fn vision_ui_exit_animation_start(ui: *mut vision_ui_t);
    pub fn vision_ui_enter_animation_is_finished(ui: *const vision_ui_t) -> bool;
    pub fn vision_ui_enter_animation_set_is_finished(ui: *mut vision_ui_t);
    pub fn vision_ui_enter_animation_start(ui: *mut vision_ui_t);
    #[doc = " Returns the current high-level input action from the backend.\n\n @param ui UI instance whose driver state should be queried. Must not be `NULL`.\n @return The current mapped action for this frame."]
    pub fn vision_ui_driver_action_get(ui: *const vision_ui_t) -> vision_ui_action_t;
    #[doc = " Returns a monotonic millisecond tick value.\n\n @param ui UI instance whose driver state should be queried. Must not be `NULL`.\n @return A monotonic time value in milliseconds."]
    pub fn vision_ui_driver_ticks_ms_get(ui: *const vision_ui_t) -> u32;
    #[doc = " Sleeps or yields for roughly the requested number of milliseconds.\n\n @param ui UI instance whose driver should perform the delay. Must not be `NULL`.\n @param ms Approximate delay duration in milliseconds."]
    pub fn vision_ui_driver_delay(ui: *const vision_ui_t, ms: u32);
    #[doc = " Stores the backend driver handle on the UI instance.\n\n @param ui UI instance to configure. Must not be `NULL`.\n @param driver Backend-specific handle to store. This pointer is borrowed, not copied."]
    pub fn vision_ui_driver_bind(ui: *mut vision_ui_t, driver: *mut ::std::os::raw::c_void);
    #[doc = " Activates a backend font for subsequent text operations.\n\n @param ui UI instance whose backend font should change. Must not be `NULL`.\n @param font Font configuration to activate."]
    pub fn vision_ui_driver_font_set(ui: *mut vision_ui_t, font: vision_ui_font_t);
    #[doc = " Returns the backend font that is currently active.\n\n @param ui UI instance whose backend font should be queried. Must not be `NULL`.\n @return A copy of the active backend font configuration. Its `font` field may be `NULL` if no font is active yet."]
    pub fn vision_ui_driver_font_get(ui: *const vision_ui_t) -> vision_ui_font_t;
    #[doc = " Draws plain text using the currently active font.\n\n @param ui UI instance whose driver should draw the text. Must not be `NULL`.\n @param x Left position in pixels.\n @param y Baseline position in pixels.\n @param str Borrowed NUL-terminated plain-text string to draw."]
    pub fn vision_ui_driver_str_draw(
        ui: *const vision_ui_t,
        x: u16,
        y: u16,
        str_: *const ::std::os::raw::c_char,
    );
    #[doc = " Draws UTF-8 text using the currently active font.\n\n @param ui UI instance whose driver should draw the text. Must not be `NULL`.\n @param x Left position in pixels.\n @param y Baseline position in pixels.\n @param str Borrowed NUL-terminated UTF-8 string to draw."]
    pub fn vision_ui_driver_str_utf8_draw(
        ui: *const vision_ui_t,
        x: u16,
        y: u16,
        str_: *const ::std::os::raw::c_char,
    );
    #[doc = " Returns the rendered width of plain text.\n\n @param ui UI instance whose driver should measure the text. Must not be `NULL`.\n @param str Borrowed NUL-terminated plain-text string to measure.\n @return Width in pixels."]
    pub fn vision_ui_driver_str_width_get(
        ui: *const vision_ui_t,
        str_: *const ::std::os::raw::c_char,
    ) -> u16;
    #[doc = " Returns the rendered width of UTF-8 text.\n\n @param ui UI instance whose driver should measure the text. Must not be `NULL`.\n @param str Borrowed NUL-terminated UTF-8 string to measure.\n @return Width in pixels."]
    pub fn vision_ui_driver_str_utf8_width_get(
        ui: *const vision_ui_t,
        str_: *const ::std::os::raw::c_char,
    ) -> u16;
    #[doc = " Returns the current text height for the active font.\n\n @param ui UI instance whose driver should be queried. Must not be `NULL`.\n @return Text height in pixels for the active backend font."]
    pub fn vision_ui_driver_str_height_get(ui: *const vision_ui_t) -> u16;
    #[doc = " Draws a single pixel.\n\n @param ui UI instance whose driver should draw. Must not be `NULL`.\n @param x X coordinate in pixels.\n @param y Y coordinate in pixels."]
    pub fn vision_ui_driver_pixel_draw(ui: *const vision_ui_t, x: u16, y: u16);
    #[doc = " Draws a circle outline.\n\n @param ui UI instance whose driver should draw. Must not be `NULL`.\n @param x Circle center X coordinate in pixels.\n @param y Circle center Y coordinate in pixels.\n @param r Circle radius in pixels."]
    pub fn vision_ui_driver_circle_draw(ui: *const vision_ui_t, x: u16, y: u16, r: u16);
    #[doc = " Draws a filled circle.\n\n @param ui UI instance whose driver should draw. Must not be `NULL`.\n @param x Circle center X coordinate in pixels.\n @param y Circle center Y coordinate in pixels.\n @param r Circle radius in pixels."]
    pub fn vision_ui_driver_disc_draw(ui: *const vision_ui_t, x: u16, y: u16, r: u16);
    #[doc = " Draws a rounded filled rectangle.\n\n @param ui UI instance whose driver should draw. Must not be `NULL`.\n @param x Left position in pixels.\n @param y Top position in pixels.\n @param w Width in pixels.\n @param h Height in pixels.\n @param r Corner radius in pixels."]
    pub fn vision_ui_driver_box_r_draw(
        ui: *const vision_ui_t,
        x: u16,
        y: u16,
        w: u16,
        h: u16,
        r: u16,
    );
    #[doc = " Draws a filled rectangle.\n\n @param ui UI instance whose driver should draw. Must not be `NULL`.\n @param x Left position in pixels.\n @param y Top position in pixels.\n @param w Width in pixels.\n @param h Height in pixels."]
    pub fn vision_ui_driver_box_draw(ui: *const vision_ui_t, x: u16, y: u16, w: u16, h: u16);
    #[doc = " Draws a rectangular outline.\n\n @param ui UI instance whose driver should draw. Must not be `NULL`.\n @param x Left position in pixels.\n @param y Top position in pixels.\n @param w Width in pixels.\n @param h Height in pixels."]
    pub fn vision_ui_driver_frame_draw(ui: *const vision_ui_t, x: u16, y: u16, w: u16, h: u16);
    #[doc = " Draws a rounded rectangular outline.\n\n @param ui UI instance whose driver should draw. Must not be `NULL`.\n @param x Left position in pixels.\n @param y Top position in pixels.\n @param w Width in pixels.\n @param h Height in pixels.\n @param r Corner radius in pixels."]
    pub fn vision_ui_driver_frame_r_draw(
        ui: *const vision_ui_t,
        x: u16,
        y: u16,
        w: u16,
        h: u16,
        r: u16,
    );
    #[doc = " Draws a horizontal line.\n\n @param ui UI instance whose driver should draw. Must not be `NULL`.\n @param x Left position in pixels.\n @param y Y coordinate in pixels.\n @param l Length in pixels."]
    pub fn vision_ui_driver_line_h_draw(ui: *const vision_ui_t, x: u16, y: u16, l: u16);
    #[doc = " Draws a vertical line.\n\n @param ui UI instance whose driver should draw. Must not be `NULL`.\n @param x X coordinate in pixels.\n @param y Top position in pixels.\n @param h Height in pixels."]
    pub fn vision_ui_driver_line_v_draw(ui: *const vision_ui_t, x: u16, y: u16, h: u16);
    #[doc = " Draws an arbitrary line segment.\n\n @param ui UI instance whose driver should draw. Must not be `NULL`.\n @param x1 Start X coordinate in pixels.\n @param y1 Start Y coordinate in pixels.\n @param x2 End X coordinate in pixels.\n @param y2 End Y coordinate in pixels."]
    pub fn vision_ui_driver_line_draw(ui: *const vision_ui_t, x1: u16, y1: u16, x2: u16, y2: u16);
    #[doc = " Draws a dotted horizontal line.\n\n @param ui UI instance whose driver should draw. Must not be `NULL`.\n @param x Left position in pixels.\n @param y Y coordinate in pixels.\n @param l Length in pixels."]
    pub fn vision_ui_driver_line_h_dotted_draw(ui: *const vision_ui_t, x: u16, y: u16, l: u16);
    #[doc = " Draws a dotted vertical line.\n\n @param ui UI instance whose driver should draw. Must not be `NULL`.\n @param x X coordinate in pixels.\n @param y Top position in pixels.\n @param h Height in pixels."]
    pub fn vision_ui_driver_line_v_dotted_draw(ui: *const vision_ui_t, x: u16, y: u16, h: u16);
    #[doc = " Draws a monochrome bitmap.\n\n @param ui UI instance whose driver should draw. Must not be `NULL`.\n @param x Left position in pixels.\n @param y Top position in pixels.\n @param w Bitmap width in pixels.\n @param h Bitmap height in pixels.\n @param bit_map Borrowed bitmap data pointer. The pointed-to bitmap should remain valid for the duration of the draw\n call."]
    pub fn vision_ui_driver_bmp_draw(
        ui: *const vision_ui_t,
        x: u16,
        y: u16,
        w: u16,
        h: u16,
        bit_map: *const u8,
    );
    #[doc = " Changes the current draw color.\n\n @param ui UI instance whose driver state should change. Must not be `NULL`.\n @param color Backend-specific draw color value."]
    pub fn vision_ui_driver_color_draw(ui: *const vision_ui_t, color: u8);
    #[doc = " Changes the backend text drawing mode.\n\n @param ui UI instance whose driver state should change. Must not be `NULL`.\n @param mode Backend-specific text drawing mode."]
    pub fn vision_ui_driver_font_mode_set(ui: *const vision_ui_t, mode: u8);
    #[doc = " Changes the backend text direction.\n\n @param ui UI instance whose driver state should change. Must not be `NULL`.\n @param dir Backend-specific text direction value."]
    pub fn vision_ui_driver_font_direction_set(ui: *const vision_ui_t, dir: u8);
    #[doc = " Restricts drawing to a rectangular clip region.\n\n @param ui UI instance whose driver state should change. Must not be `NULL`.\n @param x0 Clip region start X coordinate.\n @param y0 Clip region start Y coordinate.\n @param x1 Clip region end X coordinate.\n @param y1 Clip region end Y coordinate."]
    pub fn vision_ui_driver_clip_window_set(
        ui: *const vision_ui_t,
        x0: i16,
        y0: i16,
        x1: i16,
        y1: i16,
    );
    #[doc = " Clears the current clip region.\n\n @param ui UI instance whose driver state should change. Must not be `NULL`."]
    pub fn vision_ui_driver_clip_window_reset(ui: *const vision_ui_t);
    #[doc = " Clears the full frame buffer.\n\n @param ui UI instance whose driver should clear the buffer. Must not be `NULL`."]
    pub fn vision_ui_driver_buffer_clear(ui: *const vision_ui_t);
    #[doc = " Presents the current frame buffer.\n\n @param ui UI instance whose driver should present the buffer. Must not be `NULL`."]
    pub fn vision_ui_driver_buffer_send(ui: *const vision_ui_t);
    #[doc = " Presents only a sub-rectangle of the frame buffer if the backend supports it.\n\n @param ui UI instance whose driver should present the buffer. Must not be `NULL`.\n @param x Left position of the dirty rectangle.\n @param y Top position of the dirty rectangle.\n @param w Width of the dirty rectangle.\n @param h Height of the dirty rectangle."]
    pub fn vision_ui_driver_buffer_area_send(
        ui: *const vision_ui_t,
        x: u16,
        y: u16,
        w: u16,
        h: u16,
    );
    #[doc = " Returns a readable pointer to the full-size frame buffer used by transition and blur effects.\n\n @param ui UI instance whose driver buffer should be queried. Must not be `NULL`.\n @return A pointer to the readable full-size frame buffer when the backend exposes one. Backends that cannot expose a\n readable full buffer may return `NULL` or another unusable pointer for transition/blur effects, in which case those\n effects are not fully supported.\n\n @attention this should be a full size buffer"]
    pub fn vision_ui_driver_buffer_pointer_get(
        ui: *const vision_ui_t,
    ) -> *mut ::std::os::raw::c_void;
    pub fn vision_ui_to_list_switch_item(
        list_item: *mut vision_ui_list_item_t,
    ) -> *mut vision_ui_switch_item_t;
    pub fn vision_ui_to_list_slider_item(
        list_item: *mut vision_ui_list_item_t,
    ) -> *mut vision_ui_slider_item_t;
    pub fn vision_ui_to_list_icon_item(
        list_item: *mut vision_ui_list_item_t,
    ) -> *mut vision_ui_icon_item_t;
    pub fn vision_ui_to_list_user_item(
        list_item: *mut vision_ui_list_item_t,
    ) -> *mut vision_ui_user_item_t;
    #[doc = " Creates a plain list container that can hold child items.\n\n @param ui UI instance whose allocator and ownership list should be used. Must not be `NULL`.\n @param capacity Maximum number of direct child items this list can hold.\n @param icon_mode Set to `true` to make this list accept icon-view children only.\n @param content Borrowed NUL-terminated label pointer stored on the item. The pointed-to string should remain valid\n while the item is in use.\n @return A non-`NULL` item on success, or `NULL` when allocating the item or its child array fails."]
    pub fn vision_ui_list_item_new(
        ui: *const vision_ui_t,
        capacity: usize,
        icon_mode: bool,
        content: *const ::std::os::raw::c_char,
    ) -> *mut vision_ui_list_item_t;
    #[doc = " Creates a non-interactive title row.\n\n @param ui UI instance whose allocator and ownership list should be used. Must not be `NULL`.\n @param title Borrowed NUL-terminated title string stored on the item. The pointed-to string should remain valid\n while the item is in use.\n @return A non-`NULL` item on success, or `NULL` when allocating the item fails."]
    pub fn vision_ui_list_title_item_new(
        ui: *const vision_ui_t,
        title: *const ::std::os::raw::c_char,
    ) -> *mut vision_ui_list_item_t;
    #[doc = " Creates a selectable icon card, optionally with child items.\n\n @param ui UI instance whose allocator and ownership list should be used. Must not be `NULL`.\n @param capacity Maximum number of direct child items this icon item can hold.\n @param icon Borrowed monochrome bitmap pointer stored on the item. The pointed-to bitmap should remain valid while\n the item is in use.\n @param title Borrowed NUL-terminated title string stored on the item. The pointed-to string should remain valid\n while the item is in use.\n @param description Borrowed NUL-terminated description string stored on the item. The pointed-to string should remain\n valid while the item is in use.\n @return A non-`NULL` item on success, or `NULL` when allocating the item or its child array fails."]
    pub fn vision_ui_list_icon_item_new(
        ui: *const vision_ui_t,
        capacity: usize,
        icon: *const u8,
        title: *const ::std::os::raw::c_char,
        description: *const ::std::os::raw::c_char,
    ) -> *mut vision_ui_list_item_t;
    #[doc = " Creates a switch row whose callback runs when the value changes.\n\n @param ui UI instance whose allocator and ownership list should be used. Must not be `NULL`.\n @param content Borrowed NUL-terminated label string stored on the item. The pointed-to string should remain valid\n while the item is in use.\n @param default_value Initial switch value.\n @param on_changed Optional callback invoked after the switch value changes.\n @param user_data Borrowed callback context pointer stored on the item. The pointed-to data should remain valid while\n the item is in use.\n @return A non-`NULL` item on success, or `NULL` when allocating the item fails."]
    pub fn vision_ui_list_switch_item_new(
        ui: *const vision_ui_t,
        content: *const ::std::os::raw::c_char,
        default_value: bool,
        on_changed: vision_ui_switch_changed_cb,
        user_data: *mut ::std::os::raw::c_void,
    ) -> *mut vision_ui_list_item_t;
    #[doc = " Creates a numeric slider row.\n\n @param ui UI instance whose allocator and ownership list should be used. Must not be `NULL`.\n @param content Borrowed NUL-terminated label string stored on the item. The pointed-to string should remain valid\n while the item is in use.\n @param default_value Initial slider value.\n @param step Slider step size used when the value changes.\n @param min Minimum slider value.\n @param max Maximum slider value.\n @param on_changed Optional callback invoked after the slider value changes.\n @param user_data Borrowed callback context pointer stored on the item. The pointed-to data should remain valid while\n the item is in use.\n @return A non-`NULL` item on success, or `NULL` when allocating the item fails."]
    pub fn vision_ui_list_slider_item_new(
        ui: *const vision_ui_t,
        content: *const ::std::os::raw::c_char,
        default_value: i16,
        step: u8,
        min: i16,
        max: i16,
        on_changed: vision_ui_slider_changed_cb,
        user_data: *mut ::std::os::raw::c_void,
    ) -> *mut vision_ui_list_item_t;
    #[doc = " Creates a full-screen user scene that takes over drawing while selected.\n\n @param ui UI instance whose allocator and ownership list should be used. Must not be `NULL`.\n @param content Borrowed NUL-terminated label string stored on the item. The pointed-to string should remain valid\n while the item is in use.\n @param init_function Optional callback run the first time the user item becomes active.\n @param loop_function Optional callback run every frame while the user item is active.\n @param exit_function Optional callback run when leaving the user item.\n @param user_data Borrowed callback context pointer shared by the scene callbacks. The pointed-to data should remain\n valid while the item is in use.\n @return A non-`NULL` item on success, or `NULL` when allocating the item fails."]
    pub fn vision_ui_list_user_item_new(
        ui: *const vision_ui_t,
        content: *const ::std::os::raw::c_char,
        init_function: vision_ui_scene_cb,
        loop_function: vision_ui_scene_cb,
        exit_function: vision_ui_scene_cb,
        user_data: *mut ::std::os::raw::c_void,
    ) -> *mut vision_ui_list_item_t;
    #[doc = " Sets the root list displayed by the UI.\n\n @param ui UI instance to configure. Must not be `NULL`.\n @param item Root list item to attach by pointer. The item is not copied.\n @return `true` when `item` was accepted, or `false` when `item` is `NULL`.\n\n @note If `item` was created with Vision UI item constructors for the same `ui`, `vision_ui_destroy()` will release\n it later as part of the UI-owned item tree."]
    pub fn vision_ui_root_item_set(ui: *mut vision_ui_t, item: *mut vision_ui_list_item_t) -> bool;
    pub fn vision_ui_root_list_get(ui: *const vision_ui_t) -> *mut vision_ui_list_item_t;
    #[doc = " Appends a child item to a parent list container.\n\n @param ui UI instance whose selector/camera state may be updated. Must not be `NULL`.\n @param parent Parent list container that will receive the child by pointer. The child is not copied.\n @param child Child item to append by pointer.\n @return `true` on success. Returns `false` when `parent` or `child` is `NULL`, when `parent` is already full, when\n the maximum nesting layer would be exceeded, or when an icon-view parent receives a non-icon child."]
    pub fn vision_ui_list_push_item(
        ui: *mut vision_ui_t,
        parent: *mut vision_ui_list_item_t,
        child: *mut vision_ui_list_item_t,
    ) -> bool;
    pub fn vision_ui_selector_instance_get(ui: *const vision_ui_t) -> *const vision_ui_selector_t;
    pub fn vision_ui_selector_mutable_instance_get(
        ui: *mut vision_ui_t,
    ) -> *mut vision_ui_selector_t;
    pub fn vision_ui_selector_t_selector_bind_item(
        ui: *mut vision_ui_t,
        item: *mut vision_ui_list_item_t,
    ) -> bool;
    pub fn vision_ui_selector_go_next_item(ui: *mut vision_ui_t);
    pub fn vision_ui_selector_go_prev_item(ui: *mut vision_ui_t);
    pub fn vision_ui_selector_jump_to_selected_item(ui: *mut vision_ui_t);
    pub fn vision_ui_selector_exit_current_item(ui: *mut vision_ui_t);
    pub fn vision_ui_camera_instance_get(ui: *const vision_ui_t) -> *const vision_ui_camera_t;
    pub fn vision_ui_camera_mutable_instance_get(ui: *mut vision_ui_t) -> *mut vision_ui_camera_t;
    pub fn vision_ui_camera_instance_x_trg_set(ui: *mut vision_ui_t, x_trg: f32);
    pub fn vision_ui_camera_instance_y_trg_set(ui: *mut vision_ui_t, y_trg: f32);
    pub fn vision_ui_camera_bind_selector(
        ui: *mut vision_ui_t,
        selector: *mut vision_ui_selector_t,
    );
    pub fn vision_ui_exit_animation_render(ui: *mut vision_ui_t, delta_ms: f32);
    pub fn vision_ui_enter_animation_render(ui: *mut vision_ui_t, delta_ms: f32);
    pub fn vision_ui_widget_render(ui: *mut vision_ui_t);
    pub fn vision_ui_list_render(ui: *mut vision_ui_t);
    pub fn vision_ui_notification_instance_get(
        ui: *const vision_ui_t,
    ) -> *const vision_ui_notification_t;
    pub fn vision_ui_notification_mutable_instance_get(
        ui: *mut vision_ui_t,
    ) -> *mut vision_ui_notification_t;
    #[doc = " Shows a transient notification bar for the given duration in milliseconds.\n\n If another notification is already running, the new message is queued as the pending replacement.\n\n @param ui UI instance that owns the notification state. Must not be `NULL`.\n @param content Borrowed NUL-terminated message string used for layout and rendering. The pointed-to string should\n remain valid while the notification is visible or pending.\n @param span Display duration in milliseconds."]
    pub fn vision_ui_notification_push(
        ui: *mut vision_ui_t,
        content: *const ::std::os::raw::c_char,
        span: u16,
    );
    pub fn vision_ui_alert_instance_get(ui: *const vision_ui_t) -> *const vision_ui_alert_t;
    pub fn vision_ui_alert_mutable_instance_get(ui: *mut vision_ui_t) -> *mut vision_ui_alert_t;
    #[doc = " Shows a centered alert for the given duration in milliseconds.\n\n @param ui UI instance that owns the alert state. Must not be `NULL`.\n @param content Borrowed NUL-terminated message string used for layout and rendering. The pointed-to string should\n remain valid while the alert is visible.\n @param span Display duration in milliseconds."]
    pub fn vision_ui_alert_push(
        ui: *mut vision_ui_t,
        content: *const ::std::os::raw::c_char,
        span: u16,
    );
    #[doc = " Built-in list icon pack used by the simulator and default renderer setup."]
    pub static mut DEFAULT_LIST_ICON: vision_ui_icon_t;
    #[doc = " Replaces the active list icon pack.\n\n @param ui UI instance to configure. Must not be `NULL`.\n @param icon Icon bitmap pack to store by value.\n\n @note The struct is copied by value, but any bitmap pointers inside it remain borrowed and should stay valid while\n the icon pack is active."]
    pub fn vision_ui_list_icon_set(ui: *mut vision_ui_t, icon: vision_ui_icon_t);
    pub fn vision_ui_list_icon_get_current(ui: *const vision_ui_t) -> vision_ui_icon_t;
}
