//
// Created by Finn Sheng (Ziheng Sheng) on 11/10/25.
//

#ifndef VISION_UI_VISION_UI_CONFIG_H
#define VISION_UI_VISION_UI_CONFIG_H

#define VISION_UI_ALLOW_EXIT_BY_USER 0 // 允许用户在最浅层级退出vision ui lite
#define VISION_UI_LIST_ROOT_ICON_VIEW 0
// control whether items animate into place when a new list opens
#define VISION_UI_LIST_ENTRY_ANIMATION 0

/*** 列表项 ***/
#define VISION_UI_LIST_ROOT_CAPACITY 10
#define VISION_UI_MAX_LIST_LAYER 10

/*** 通知栏 ***/
#define VISION_UI_NOTIFICATION_HEIGHT 15
#define VISION_UI_NOTIFICATION_WIDTH 20

/*** 弹窗 ***/
#define VISION_UI_ALERT_HEIGHT 20
#define VISION_UI_ALERT_WIDTH 20

#define VISION_UI_SCREEN_HEIGHT 64
#define VISION_UI_SCREEN_WIDTH 128

// timing
#define VISION_UI_LIST_TEXT_SCROLL_PAUSE_MS 1000
#define VISION_UI_LIST_TEXT_SCROLL_SPEED_PX_S 15
#define VISION_UI_LIST_SLIDER_VALUE_SCROLL_SPEED_PX_S 5
#define VISION_UI_LIST_SLIDER_VALUE_SCROLL_PAUSE_MS 1500

#define VISION_UI_ICON_VIEW_SCROLL_SPEED 90

#define VISION_UI_EXIT_ANIMATION_DURATION_MS 120
#define VISION_UI_ENTER_ANIMATION_DURATION_MS 120

#define VISION_UI_NOTIFICATION_DISMISS_DURATION_MS 400

// paddings
#define VISION_UI_LIST_TITLE_TO_DISPLAY_TOP_PADDING 0
#define VISION_UI_LIST_TITLE_TO_FRAME_PADDING 4

#define VISION_UI_LIST_FRAME_BETWEEN_PADDING 2

#define VISION_UI_LIST_FOOTER_CENTER_TO_SCROLL_BAR_PADDING 10
#define VISION_UI_LIST_FOOTER_TO_LEFT_PADDING 10

#define VISION_UI_LIST_HEADER_TO_TEXT_PADDING 2
#define VISION_UI_LIST_HEADER_TO_LEFT_DISPLAY_PADDING 4

#define VISION_UI_LIST_SELECTOR_TO_INNER_WIDGET_PADDING 3

#define VISION_UI_ICON_VIEW_ITEM_SPACING 15 // horizontal
#define VISION_UI_ICON_VIEW_TITLE_BAR_TO_LEFT_DISPLAY_PADDING 0 // horizontal
#define VISION_UI_ICON_VIEW_TITLE_BAR_TO_TITLE_PADDING 4 // horizontal
#define VISION_UI_ICON_VIEW_TITLE_TO_RIGHT_DISPLAY_MIN_PADDING 5 // horizontal
#define VISION_UI_ICON_VIEW_ICON_TO_TOP_DISPLAY_PADDING 2 // vertical
#define VISION_UI_ICON_VIEW_ICON_TO_TITLE_AREA_PADDING 2 // vertical
#define VISION_UI_ICON_VIEW_TITLE_AREA_TO_DESCRIPTION_PADDING 3 // vertical
#define VISION_UI_ICON_VIEW_DESCRIPTION_TO_DISPLAY_MIN_SPACING 3 // horizontal

// fixed sizes
#define VISION_UI_LIST_FOOTER_MAX_HEIGHT 11
#define VISION_UI_LIST_FOOTER_MAX_WIDTH 19
#define VISION_UI_LIST_HEADER_MAX_HEIGHT 7
#define VISION_UI_LIST_HEADER_MAX_WIDTH 7
#define VISION_UI_LIST_FRAME_FIXED_HEIGHT 15

#define VISION_UI_ICON_VIEW_ICON_SIZE 30
#define VISION_UI_ICON_VIEW_TITLE_AREA_HEIGHT 13
#define VISION_UI_ICON_VIEW_TITLE_BAR_WIDTH 4

#define VISION_UI_LIST_SELECTOR_FIXED_HEIGHT 15

// fixed properties
#define VISION_UI_LIST_SCROLL_BAR_WIDTH 3
#define VISION_UI_LIST_SCROLL_BAR_ANIMATION_SPEED 92

// ********** DO NOT EDIT LINES BELOW **********

// derived properties
#define VISION_UI_LIST_FOOTER_TO_SCROLL_BAR_PADDING                                                                                        \
    (VISION_UI_LIST_FOOTER_CENTER_TO_SCROLL_BAR_PADDING - VISION_UI_LIST_FOOTER_MAX_WIDTH / 2)
#define VISION_UI_LIST_TEXT_MAX_WIDTH                                                                                                      \
    (VISION_UI_SCREEN_WIDTH - VISION_UI_LIST_FOOTER_TO_SCROLL_BAR_PADDING - VISION_UI_LIST_FOOTER_MAX_WIDTH -                              \
     VISION_UI_LIST_FOOTER_TO_LEFT_PADDING - VISION_UI_LIST_HEADER_TO_TEXT_PADDING - VISION_UI_LIST_HEADER_MAX_WIDTH -                     \
     VISION_UI_LIST_HEADER_TO_LEFT_DISPLAY_PADDING)

#endif // VISION_UI_VISION_UI_CONFIG_H
