//
// Created by Finn Sheng (Ziheng Sheng) on 11/10/25.
//

#ifndef VISION_UI_VISION_UI_CONFIG_H
#define VISION_UI_VISION_UI_CONFIG_H

#define VISION_UI_ALLOW_EXIT_BY_USER 0 // 允许用户在最浅层级退出vision ui lite

/*** 列表项 ***/
#define VISION_UI_LIST_ROOT_CAPACITY 10
#define VISION_UI_MAX_LIST_LAYER 10

/*** 通知栏 ***/
#define VISION_UI_NOTIFICATION_HEIGHT 15
#define VISION_UI_NOTIFICATION_WIDTH 20

/*** 弹窗 ***/
#define VISION_UI_ALERT_HEIGHT 20
#define VISION_UI_ALERT_WIDTH 20

#define VISION_UI_SCREEN_HEIGHT 64
#define VISION_UI_SCREEN_WIDTH 128

// timing
#define VISION_UI_LIST_TEXT_SCROLL_PAUSE_MS 1000
#define VISION_UI_LIST_TEXT_SCROLL_SPEED_PX_S 15
#define VISION_UI_LIST_SLIDER_VALUE_SCROLL_SPEED_PX_S 5
#define VISION_UI_LIST_SLIDER_VALUE_SCROLL_PAUSE_MS 1500

// paddings
#define VISION_UI_LIST_TITLE_TO_DISPLAY_TOP_PADDING 0
#define VISION_UI_LIST_TITLE_TO_FRAME_PADDING 4

#define VISION_UI_LIST_FRAME_BETWEEN_PADDING 2

#define VISION_UI_LIST_FOOTER_CENTER_TO_SCROLL_BAR_PADDING 10
#define VISION_UI_LIST_FOOTER_TO_LEFT_PADDING 10

#define VISION_UI_LIST_HEADER_TO_TEXT_PADDING 2
#define VISION_UI_LIST_HEADER_TO_LEFT_DISPLAY_PADDING 4

#define VISION_UI_LIST_SELECTOR_TO_INNER_WIDGET_PADDING 3

// fixed sizes
#define VISION_UI_LIST_FOOTER_MAX_HEIGHT 11
#define VISION_UI_LIST_FOOTER_MAX_WIDTH 19
#define VISION_UI_LIST_HEADER_MAX_HEIGHT 7
#define VISION_UI_LIST_HEADER_MAX_WIDTH 7
#define VISION_UI_LIST_FRAME_FIXED_HEIGHT 15

#define VISION_UI_LIST_SELECTOR_FIXED_HEIGHT 15

// fixed properties
#define VISION_UI_LIST_SCROLL_BAR_WIDTH 3
#define VISION_UI_LIST_SCROLL_BAR_ANIMATION_SPEED 92

// ********** DO NOT EDIT LINES BELOW **********

// derived properties
#define VISION_UI_LIST_FOOTER_TO_SCROLL_BAR_PADDING                                                                                        \
    (VISION_UI_LIST_FOOTER_CENTER_TO_SCROLL_BAR_PADDING - VISION_UI_LIST_FOOTER_MAX_WIDTH / 2)
#define VISION_UI_LIST_TEXT_MAX_WIDTH                                                                                                      \
    (VISION_UI_SCREEN_WIDTH - VISION_UI_LIST_FOOTER_TO_SCROLL_BAR_PADDING - VISION_UI_LIST_FOOTER_MAX_WIDTH -                              \
     VISION_UI_LIST_FOOTER_TO_LEFT_PADDING - VISION_UI_LIST_HEADER_TO_TEXT_PADDING - VISION_UI_LIST_HEADER_MAX_WIDTH -                     \
     VISION_UI_LIST_HEADER_TO_LEFT_DISPLAY_PADDING)

#endif // VISION_UI_VISION_UI_CONFIG_H
