name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release

          # Add official LLVM APT repo
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20

          # Install SDL2 and other dependencies
          sudo apt-get install -y xmake libsdl2-dev
          
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-20 100
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-20 100
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-20 100
          

      - name: Configure project
        run: xmake f -y

      - name: Generate compilation database
        run: xmake project -k compile_commands

      - name: Clang-Format check
        run: |
          set -e
          files=$(git ls-files '*.c' '*.cc' '*.cpp' '*.cxx' '*.h' '*.hpp' '*.hh' '*.hxx')
          if [ -n "$files" ]; then
            clang-format --style=file --dry-run --Werror $files
          fi

      - name: Clang-Tidy check
        run: |
          find . -type f \( -name '*.c' -o -name '*.cpp' \) \
          ! -path '*/components/*' \
          | xargs clang-tidy -p . --warnings-as-errors='*'

      - name: Build
        run: xmake
